### ISSUE TITLE
how to install this plugin?

### ISSUE THREAD

**Issue by dhanashri-innovision** [m-r-s/hearingaid-prototype#24]
Hi,
We have tested the openmha on our windows PC. It works fine. Now we want to install your plugin. How to do it?

**Comment by m-r-s** [comment]
Hi,

which plugin do you mean?

Here, we offer instructions how to install and run openMHA on a Raspberry Pi based hearing aid prototype plus a pre-configured SD-card image to do so.
We only use the standard openMHA plugins.

**Comment by dhanashri-innovision** [comment]
Hi,
I want to test m-r-s hearing aid with the .wav file on my PC, with openMHA but without Raspberry Pi prototype.
so for that I will have to install these prototype. can you direct me?

**Comment by m-r-s** [comment]
The idea of this repository is to give you instructions on how to build your own physical, wearable hearing aid prototype, but not about running openMHA on a PC.

I would not recommend that, but if you really want to run the prototype-openMHA-config on your PC you could just use the provided [openMHA.cfg](https://github.com/m-r-s/hearingaid-prototype/blob/master/openMHA.cfg) with openMHA.
However, this is a very basic configuration which only runs a dynamic compressor with all gains set to zero.
Also, you then need to make sure that you properly calibrated your setup, c.f., [OpenMHA calibration manual](http://www.openmha.org/docs/openMHA_calibration_manual.pdf)
