### ISSUE TITLE
(mhafw_lib) IO error: (mhajack) Unable to connect to JACK server 'default' as client 'MHA'.

### ISSUE THREAD

**Issue by chozillla** [m-r-s/hearingaid-prototype#26]
I had this issue when I tried to run gain_live_getting_started.cfg. I deleted jack2 and redownladed it.
Another separate issue that prompted me to delete jack2 in the first place is how do you set the buffer size in Jack? Jack had it set at 512 and openMHA wanted 64.

**Comment by m-r-s** [comment]
Do you want to use openMHA on your PC, or do you use our recommended setup with the Raspberry Pi 3?

If you want to learn how to use openMHA, I would recommend you to begin with the "openMHA starting guide" http://www.openmha.org/docs/openMHA_starting_guide.pdf

**Comment by chozillla** [comment]
Currently running this on Mac OS Mojave. I haven’t found anything on this in the documentation

**Comment by m-r-s** [comment]
Okay, this project is only about the hearing aid prototype based on the Raspberry Pi 3 platform.
We use openMHA for our project, but we can't help you with the general usage.
You might head over to the openMHA project repository where you can also find instructions how to install openMHA on Mac OS: https://github.com/HoerTech-gGmbH/openMHA/blob/master/INSTALLATION.md#ii-macos-installer
You can also open an issue over there.
