### ISSUE TITLE
Detailed Quick start

### ISSUE THREAD

**Issue by Prototypemax** [m-r-s/hearingaid-prototype#3]
Moin Marc,
habe gerade versucht im Wiki die Seite "Detailed Quick start" zu erstellen. Bekomme allerdings den Fehler 404 bei speichern der Seite und Github schlägt mir vor, dich zu kontaktieren. Vielleicht weißt du ja weiter?

Lg
Max

**Comment by m-r-s** [comment]
Läuft jetzt :)
